algorandfoundation/algokit-core

- Cargo.lock
- crates/algo_models/Cargo.toml
- crates/algo_models/src/lib.rs
- crates/algo_models_ffi/src/lib.rs
This PR migrates away from a reliance on `ByteBuf` within `algo_models`. The main driver for this change is to make the Rust lib more idiomatic and to provide a fixed-length array where fields must be a specific length. The interfaces exposed by `algo_models_ffi` are the same, but there will now be an error thrown on specific fields when it's not the correct length (i.e. pubkey is not 32 bytes). 
This was largely made possible (or rather, made easy) by ditching `serde_bytes` and using [serde_with::Bytes](https://docs.rs/serde_with/latest/serde_with/struct.Bytes.html) instead
> feat(algo_models)!: use [u8; n] and Vec<u8> for byte fields

- .github/workflows/python.yml
- .github/workflows/swift_ci.yml
- .github/workflows/typescript_ci.yml
Removing paths for now because they can be a bit hard to manage. Rather have CI run often rather than not run when it should (for now at least)
> ci: remove paths

- packages/typescript/algo_models/package.json
During testing of react native not having a main or module defined caused problems. This defines both to be the wasm2js bundle, which is probably the safest bet for any consumer that doesn't support exports. Now confirmed to be working with react native.
> feat(typescript): define main and module

- Cargo.toml
- crates/algokit_transact/Cargo.toml
- crates/algokit_transact_ffi/Cargo.toml
- crates/uniffi-bindgen/Cargo.toml
This will help ensure all crates use these same versions. There may be other crates we want to add here, but for now I focued on the FFI-related crates
> chore: add workspace deps

- Cargo.lock
- crates/algokit_transact_ffi/Cargo.toml
- crates/algokit_transact_ffi/src/lib.rs
~~This PR is dependent on #52. Will move out of draft mode, once it's merged.~~
This PR adds the FFI implementation of the the newly added `txn.id` and `txn.raw_id` methods.
> feat: added txnid ffi endpoints

- .github/workflows/swift_ci.yml
- crates/algokit_transact_ffi/polytest.toml
- scripts/build/index.ts
Disables swift from build script, CI, and polytest while we focus on Python and TypeScript. Main goal is to reduce noise and CI time.
> chore: temporarily disable swift

- .gitignore
- crates/algokit_transact_ffi/src/lib.rs
AK-249
Updated the get txn ids function signatures based on [this comment from the previous PR](https://github.com/algorandfoundation/algokit-core/pull/54#discussion_r2053404338). This PR change the arguments to be non-encoded txns.
> refactor: changed txn id ffi fns to accept non encoded txn arg

- crates/algokit_transact_ffi/polytest.toml
- crates/algokit_transact_ffi/test_plan.md
- packages/python/algokit_transact/tests/test_payment.py
- packages/typescript/algokit_transact/__tests__/payment.test.ts
I'm using the test transaction data that is included in the json file, however I think it makes sense to share the test data we'll expose in the object mother / test data factory.
> chore: adding ts and py test for transaction id

- api/oas_templates/typescript/api/api.mustache
- api/oas_templates/typescript/http/http.mustache
- api/oas_templates/typescript/http/isomorphic-fetch.mustache
- api/oas_templates/typescript/types/ObjectParamAPI.mustache
- api/oas_templates/typescript/types/ObservableAPI.mustache
- api/oas_templates/typescript/types/PromiseAPI.mustache
Update the template to expose the response context:
- Add http status text to response context
- Instead of using HttpInfo class, expose the response context directly.
The reason for this change is that in utils-ts, I found that I need access to the raw binary returned from the http call. Currently, there are methods such as `rawTransactionWithHttpInfo`  that return the `HttpInfo` (wrapper of the `ResponseContext`), there are some limitations:
- when processing the response, if the response type isn't binary, the text is extracted from the response. This makes the binary stream unusable downstream. In utils-ts, I can't read the binary anymore.
- `HttpInfo` is just a thin wrapper around `ResponseContext`, I think we should just expose the `ResponseContext` and the consumers have full …
> Update the template to expose the response context

- .github/workflows/ci_cd.yml
- .github/workflows/python_uniffi_ci_cd.yml
- .github/workflows/typescript_wasm_ci_cd.yml
- packages/python/algokit_transact/release.config.cjs
- packages/typescript/algokit_transact/release.config.cjs
- utils/semantic-release.cjs
This PR adds CI/CD for TypeScript via `semantic-release` for publishing to GitHub. NPM publish will come in a later PR. 
Also includes a small non-functional change to Python CI to merge artifacts, which will be useful for publishing to PyPi in a later PR
Test workflow here: https://github.com/joe-p/algokit-core/actions/runs/14794339009
Edit: Also included a fix for https://github.com/algorandfoundation/algokit-core/actions/runs/14757838024/job/41430646761
> ci: add typescript & fix semantic-release failure

- crates/algokit_transact/src/lib.rs
- crates/algokit_transact/src/test_utils/mod.rs
- crates/algokit_transact/src/tests.rs
- crates/algokit_transact/src/transactions/asset_transfer.rs
- crates/algokit_transact/src/transactions/common.rs
- crates/algokit_transact/src/transactions/mod.rs
- crates/algokit_transact/src/transactions/payment.rs
- crates/algokit_transact_ffi/src/lib.rs
When adding the builders and object mothers I noticed that when creating a transaction it felt a little redundant assigning a specific transaction type inside a transaction header, given that it's nested within the `*TransactionFields` struct and then also wrapped in an enum variant which both specify the transaction type. Additionally it was possible to create a transaction with a mismatched transaction type.
This PR removes the TransactionType enum and leverages the serde enum tag feature. The FFI trait definitions have not changed.
> feat: Remove transaction type from the transaction header struct

- .vscode/extensions.json
- packages/python/algokit_transact/poetry.toml
The VSCode mypy plugin doesn't work very well with mono repos.
This change adds a recommended plugin which automatically selects the relevant venv when navigating through different projects in a monorepo.
> chore: update config for python projects to support vscode better

- .github/workflows/python_api_client_ci_cd.yml
- .github/workflows/python_uniffi_ci_cd.yml
- Only run the steps in get_version when a release can be performed
- Add token to git checkout when running the cleanup step
> build: adjust py api ci/cd to do less when not doing a release

- crates/algokit_transact/src/constants.rs
- crates/algokit_transact/src/lib.rs
- crates/algokit_transact/src/test_utils/mod.rs
- crates/algokit_transact/src/tests.rs
- crates/algokit_transact/src/traits.rs
- crates/algokit_transact/src/transactions/mod.rs
- crates/algokit_transact_ffi/src/lib.rs
I thought this code is common enough we might want it in core.
I am still missing a way to do it in the rust crate. After I do that, the FFI crate should only re-expose what's in the core crate.
Also, I haven't taken the approach of actually signing it as it is a slow operation. I decided to attach an invalid signature, encode, and get the size.
I've also seen a bunch of times just adding `75` to the encoding length without a signature. I am assuming `75` comes up from the field name, the encoding and the signature length.
What approach do we think is best?
> feat: estimate transaction size in the FFI crate

- scripts/build/languages/typescript.ts
This seems to be an issue with Windows. When the packages are installed with `bun` and run with `npx`, the `wasm2js` command doesn't accept the `-O` flag. 
If I use `bunx` to run the command, I get the same behaviour with Mac and Linux, where it works.
I think that seen we are using `bun`, let's use `bunx` instead of `npx` for more consistent experience.
> build: use bunx instead of npx

- packages/typescript/algokit_transact/__tests__/common.ts
- packages/typescript/algokit_transact/__tests__/generic_transaction.test.ts
- packages/typescript/algokit_transact/__tests__/payment.test.ts
- packages/typescript/algokit_transact/bunfig.toml
- packages/typescript/algokit_transact/package.json
- packages/typescript/algokit_transact/src/bun.setup.ts
Initially the main and module of the package.json was set to wasm2js under the assumption that only outdated software that didn't support wasm would be using those fields over exports. This was an incorrect assumption. This commit updates main & module to use the proper WASM bundles but the wasm2js bundle is still defined under exports for react-native
> fix(typescript/algokit_transact): use node & esm bundles for main & module

- Cargo.lock
- Cargo.toml
- crates/algokit_transact/src/lib.rs
- crates/algokit_transact/src/tests.rs
- crates/algokit_transact/src/traits.rs
- crates/algokit_transact/src/transactions/mod.rs
- crates/algokit_transact_ffi/Cargo.toml
- crates/algokit_transact_ffi/polytest.toml
- crates/algokit_transact_ffi/src/lib.rs
- crates/algokit_transact_ffi/test_plan.md
- packages/python/algokit_transact/pyproject.toml
- packages/python/algokit_transact/tests/test_transaction_group.py
- packages/typescript/algokit_transact/__tests__/transaction_group.test.ts
More generically this supports a collection of transactions, so can be used with grouped or ungrouped collections of transactions.
Depends on #104
> feat: add encode, decode and sign support for transaction groups

- crates/algokit_utils/src/lib.rs
- crates/algokit_utils/src/testing/fixture.rs
- crates/algokit_utils/src/transactions/common.rs
- crates/algokit_utils/src/transactions/composer.rs
- crates/algokit_utils/src/transactions/mod.rs
- crates/algokit_utils/tests/transactions/composer/application_call.rs
- crates/algokit_utils/tests/transactions/composer/asset_config.rs
- crates/algokit_utils/tests/transactions/composer/key_registration.rs
- crates/algokit_utils/tests/transactions/composer/mod.rs
- crates/algokit_utils/tests/transactions/composer/payment.rs
- crates/algokit_utils/tests/transactions/composer/transaction_group.rs
Fixes #
- Rename “Txn” types to “Transaction”, for example “ComposerTxn”.
- Add an “add_transactions” method to the composer to support atomically adding a collection of transactions to the composer.
- composer.send returns a PendingTransactionResponse, which only contains the first transaction in the group. Instead it should return a result like utils-ts does.
Note: for composer.send, ABIResults won't be returned yet until we support ABI methods
> Composer tweaks

- crates/algokit_utils/src/testing/account_helpers.rs
- crates/algokit_utils/src/testing/fixture.rs
- crates/algokit_utils/src/transactions/common.rs
- crates/algokit_utils/src/transactions/composer.rs
- crates/algokit_utils/src/transactions/mod.rs
- crates/algokit_utils/tests/algod/pending_transaction_information.rs
- crates/algokit_utils/tests/algod/raw_transaction.rs
- crates/algokit_utils/tests/transactions/composer/payment.rs
When a signer is set in the transaction params, it should be used for signing. In this PR, I also added logic to batch signing (see `gather_signatures` function for efficiency.
> Fix custom signer for transaction

- packages/python/algokit_transact/pyproject.toml
As discussed, this PR rollbacks the python package version in the manifest to fix the python release pipeline.
It also predisposes the correct trigger `merge_group` for when we enable merge queues
> fix: python CI CD

- crates/algokit_utils/tests/transactions/composer/resource_population.rs
Gate transaction-level resource population behind ResourcePopulation::Enabled and stabilize behavior on go-algorand 4.3.0+ (access lists).
Update resource_population tests to enable access-list mode, adjust deterministic expectations (e.g., medium box refs).
NOTE: 4.3.0 on go algorand repo https://github.com/algorand/go-algorand/releases/tag/v4.3.0-stable added new access list behaviour but the release does not seem to include updates to algod open api spec (the new [access](https://github.com/algorand/go-algorand/blob/3e5d694bcadd3aaa4d1e30d208f55eec68c5638d/data/transactions/application.go#L144) field in app call txns is present in code but not in the spec for some reason). This pr mainly aims to accomodate hotfixes to patch failing resource population tests due to new behaviour in …
> fix: go-algorand 4.3.0 access list behaviour hotfixes

- crates/algokit_utils/tests/common/fixture.rs
- crates/algokit_utils/tests/kmd/key_management.rs
- crates/algokit_utils/tests/kmd/wallet_lifecycle.rs
- crates/algokit_utils_ffi/src/abi/abi_type.rs
- crates/algokit_utils_ffi/src/abi/abi_value.rs
- crates/algokit_utils_ffi/src/abi/mod.rs
- crates/algokit_utils_ffi/src/lib.rs
- crates/algokit_utils_ffi/src/transactions/app_call.rs
- crates/algokit_utils_ffi/src/transactions/asset_config.rs
- crates/algokit_utils_ffi/src/transactions/asset_freeze.rs
- crates/algokit_utils_ffi/src/transactions/asset_transfer.rs
- crates/algokit_utils_ffi/src/transactions/common.rs
- crates/algokit_utils_ffi/src/transactions/composer.rs
- crates/algokit_utils_ffi/src/transactions/key_registration.rs
- crates/algokit_utils_ffi/src/transactions/mod.rs
- crates/algokit_utils_ffi/src/transactions/payment.rs
- packages/python/algokit_utils/tests/test_utils.py
Adds support for app method calls to the composer
> feat: app method call support in ffi composer
